name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6.0.9
        name: Install pnpm
        with:
          version: latest
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: 📥 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/proxy.js
